"""
Inventory scanner — matches the matter folder's contents against the T1
template, read-only. Produces per-item PRESENT / PARTIAL / MISSING with the
matching files as evidence, and writes a markdown report to METIS_HOME.

Detection: filename match counts as strong signal; content match (first 4KB
of .md/.txt files) counts as weak signal. PRESENT = filename hit,
PARTIAL = content-only hit, MISSING = neither.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

from . import DEFAULT_MATTER, METIS_HOME
from .state_machine import MatterState, Stage
from .template_t1 import T1_ITEMS, ItemStatus

SKIP_DIRS = {".git", "node_modules", "__pycache__", ".metis-state"}
TEXT_EXT = {".md", ".txt", ".csv"}


def _iter_files(matter: Path):
    for p in sorted(matter.rglob("*")):
        if p.is_file() and not any(part in SKIP_DIRS for part in p.parts):
            yield p


def scan(matter: Path) -> list[ItemStatus]:
    files = list(_iter_files(matter))
    # Pre-read text heads once
    text_heads: dict[Path, str] = {}
    for p in files:
        if p.suffix.lower() in TEXT_EXT:
            try:
                text_heads[p] = p.read_text(encoding="utf-8", errors="ignore")[:4096].lower()
            except OSError:
                continue

    results: list[ItemStatus] = []
    for item in T1_ITEMS:
        name_hits, content_hits = [], []
        for p in files:
            fname = p.name.lower()
            if any(pat in fname for pat in item.detect_patterns):
                name_hits.append(str(p.relative_to(matter)))
                continue
            head = text_heads.get(p)
            if head and any(pat in head for pat in item.detect_patterns):
                content_hits.append(str(p.relative_to(matter)))
        if name_hits:
            results.append(ItemStatus(item, "present", name_hits))
        elif content_hits:
            results.append(ItemStatus(item, "partial", content_hits))
        else:
            results.append(ItemStatus(item, "missing"))
    return results


def report(matter: Path, results: list[ItemStatus]) -> str:
    counts = {"present": 0, "partial": 0, "missing": 0}
    for r in results:
        counts[r.state] += 1
    lines = [
        f"# Matter inventory — {matter.name} (T1: DPO / s.111C stay)",
        "",
        f"**Scanned:** {date.today().isoformat()} · read-only · "
        f"✅ {counts['present']} present · 🟡 {counts['partial']} partial · 🔴 {counts['missing']} missing",
        "",
        "| Item | Status | Source system | Retrieval | Affidavit | Evidence (top 3) |",
        "|---|---|---|---|---|---|",
    ]
    icon = {"present": "✅", "partial": "🟡", "missing": "🔴"}
    for r in results:
        ev = "<br>".join(r.evidence[:3]) if r.evidence else "—"
        refs = ", ".join(r.item.affidavit_refs) or "—"
        lines.append(
            f"| {r.item.name} | {icon[r.state]} {r.state} | {r.item.source_system} "
            f"| {r.item.retrieval} | {refs} | {ev} |"
        )
    lines += [
        "",
        "## Next actions (missing/partial items by retrieval channel)",
        "",
    ]
    for r in results:
        if r.state != "present":
            lines.append(
                f"- **{r.item.name}** → `{r.item.retrieval}` via {r.item.source_system}."
                + (f" {r.item.notes}" if r.item.notes else "")
            )
    lines += [
        "",
        "---",
        "*DRAFT — generated by Metis for the matter owner's own use. Not legal advice.*",
    ]
    return "\n".join(lines)


def run(matter: Path | None = None) -> Path:
    matter = (matter or DEFAULT_MATTER).resolve()
    if not matter.is_dir():
        raise SystemExit(f"matter folder not found: {matter}")
    results = scan(matter)
    st = MatterState(matter)
    for r in results:
        st.set_item(r.item.id, r.state, r.evidence)
    if st.stage == Stage.TRIAGE:
        st.advance(Stage.INVENTORY, "first inventory scan")
    st.save()
    out = METIS_HOME / f"INVENTORY-{matter.name.upper()}-{date.today().isoformat()}.md"
    out.write_text(report(matter, results))
    print(f"✅ inventory: {sum(1 for r in results if r.state=='present')}/{len(results)} present")
    print(f"➜ {out}")
    print(f"➜ state: {st.summary()}")
    return out


if __name__ == "__main__":
    run(Path(sys.argv[1]) if len(sys.argv) > 1 else None)
